---
title: "chipotle_purrr"
format: html
---

```{r}
pacman::p_load(tidyverse, stringr, knitr, jsonlite)
```

```{r}
popularity_day <- function(x) {

  clean <- x %>%
    str_replace_all('“', '"') %>%
    str_replace_all('”', '"')

  popularity <- jsonlite::fromJSON(clean) %>%
    enframe(name = "day", value = "visits") %>%
    mutate(visits = unlist(visits)) %>% 
    as_tibble()

  return(popularity)
}
```

```{r}
most_popular_day <- function(x) {

  popularity <- popularity_day(x)

  popularity %>%
    filter(visits == max(visits)) %>%
    pull(day) %>%
    paste(collapse = ", ")
}
```


```{r}
test1 <- "{“Monday”:39,“Tuesday”:67,“Wednesday”:420,“Thursday”:1,“Friday”:36,“Saturday”:65,“Sunday”:87}"

kable(popularity_day(test1), caption = "Test Case 1.1 - Parsed Output")
kable(most_popular_day(test1), caption = "Test Case 1.2 - Parsed Output")

```

```{r}
test2 <- "{“Monday”:104,“Tuesday”:6,“Wednesday”:121314,“Thursday”:11,“Friday”:34,“Saturday”:65,“Sunday”:200}"

kable(popularity_day(test2), caption = "Test Case 2.1 - Parsed Output")
kable(most_popular_day(test2), caption = "Test Case 2.2 - Parsed Output")

```

```{r}
test3 <- "{“Monday”:1,“Tuesday”:1,“Wednesday”:1,“Thursday”:0,“Friday”:0,“Saturday”:0,“Sunday”:0}"

kable(popularity_day(test3), caption = "Test Case 3.1 - Parsed Output")
kable(most_popular_day(test3), caption = "Test Case 3.2 - Parsed Output")
```

