---
title: "chipotle_functions"
format: html
---

```{r}
pacman::p_load(tidyverse, stringr, pander)
```

```{r}
parse_popularity <- function(x) {
  # Replace curly quotes if present
  clean <- x %>% 
    str_replace_all("“", "\"") %>% 
    str_replace_all("”", "\"")
  
  # Extract "Day":Number pairs
  pairs <- str_extract_all(clean, "\"(.*?)\":\\d+")[[1]]
  
  # Split into day and number
  tibble(
    day = str_extract(pairs, "(?<=\").+?(?=\")"),
    visits = as.numeric(str_extract(pairs, "\\d+$"))
  )
}

```

```{r}
most_popular_day <- function(x) {
  df <- parse_popularity(x)
  
  max_visits <- max(df$visits)
  
  df %>% 
    filter(visits == max_visits) %>% 
    pull(day) %>% 
    paste(collapse = ", ")
}

```

```{r}
test1 <- "{“Monday”:39,“Tuesday”:67,“Wednesday”:420,“Thursday”:1,“Friday”:36,“Saturday”:65,“Sunday”:87}"

pander(parse_popularity(test1))
pander(most_popular_day(test1))

```

```{r}
test2 <- "{“Monday”:104,“Tuesday”:6,“Wednesday”:121314,“Thursday”:11,“Friday”:34,“Saturday”:65,“Sunday”:200}"

pander(parse_popularity(test2))
pander(most_popular_day(test2))

```

```{r}
test3 <- "{“Monday”:1,“Tuesday”:1,“Wednesday”:1,“Thursday”:0,“Friday”:0,“Saturday”:0,“Sunday”:0}"

pander(parse_popularity(test3))
pander(most_popular_day(test3))
```
