---
title: "stock_task"
format: html
---

```{r message=FALSE, warning=FALSE}
library(tidyverse) 
library(readr) 
library(lubridate) 
library(janitor)
library(pander)

```

```{r}
stock_raw <- read_csv(
  "https://raw.githubusercontent.com/byuistats/data/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.csv"
) %>%
  clean_names()

# pander(stock_raw)



```

```{r}
stock_tidy <- stock_raw %>%
  clean_names() %>%
  mutate(
    month_end = str_extract(contest_period, "^[A-Za-z]+"),
    year_end = str_extract(contest_period, "[0-9]{4}") %>% as.integer()
  )

pander(stock_tidy)

```

```{r}
stock_tidy <- stock_tidy %>%
  mutate(
    month_end = str_sub(month_end, 1, 3),
    month_end = factor(month_end,
         levels = c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")))
write_rds(stock_tidy, "stock_tidy.rds")

test_read <- read_rds("stock_tidy.rds")
# glimpse(test_read)

```

```{r}
djia_table <- stock_tidy %>%
  filter(variable == "DJIA") %>%
  select(month_end, year_end, value) %>%
  pivot_wider(
    names_from = year_end,
    values_from = value
  ) %>%
  arrange(month_end)   # ensures Jan → Dec in rows


pander(djia_table)


```

```{r}

```
